#!/bin/sh
# Terminate already running bar instances
# polybar-msg cmd quit
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar bar1 &

# Launch bar1 and bar2
#polybar example &



# 运行 Polybar，使用默认的配置文件路径 ~/.config/polybar/config.ini
# polybar mybar 2>&1 | tee -a /tmp/polybar.log & disown
